# Generated by Django 3.1.5 on 2021-01-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
